cc_binary(
    name = "client",
    srcs = ["main.cc"],
    deps = [
        "@bracket//base",
        "@bracket//event",
        "@bracket//http",
        "@bracket//irc/bot:remote_service_brpc",
        "@bracket//irc/bot:remote_service_cc_proto",
    ],
)
